spring:
  datasource:
    url: jdbc:mysql://awseb-e-cahyrqyrqp-stack-awsebrdsdatabase-uakg0qooggte.ck82wv1jlji6.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
    username: youngkim
    password: Qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100 # 한번에 최대 100개(in)의 데이터를 가져오도록 쿼리(N+1 문제 해결)
  cache:
    type: redis
    redis:
      host: kotlin-board-redis-nvqkxy.serverless.apn2.cache.amazonaws.com
      port: 6379
