spring:
  datasource:
    url: jdbc:mysql://awseb-e-cahyrqyrqp-stack-awsebrdsdatabase-uakg0qooggte.ck82wv1jlji6.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
    username: youngkim
    password: Qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
