name: kotlin board

env:
  AWS_REGION: ap-northeast-2

# main 브랜치에 push가 될 때 워크플로우 실행
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production # job 실행환경
    
    steps:
    # 우분투로 소스코드 다운로드
    - name: Checkout
      uses: actions/checkout@v3

    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    # Gradle로 클린, 빌드
    - name: Build with Gradle
      run: ./gradlew clean build

    # 현재 시간 및 포맷 설정
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    # deply 폴더 생성 및 jar 파일 복사
    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cd deploy && zip -r deploy.zip .

    # AWS 인증 정보로 배포파일을 지정된 Elastic Beanstalk 환경으로 배포
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ env.AWS_REGION }}
        application_name: kotlin-board
        environment_name: Kotlin-board-env
        version_label: github-action-${{steps.current-time.outputs.formattedTime}}
        deployment_package: deploy/deploy.zip
